# Generated by Django 4.2.30 on 2026-06-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_alter_event_id_alter_registration_id_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
